--BEGIN TABLE CREATES

--paket bilgisi table'ı
CREATE TABLE SUBSCRIPTION_PACKAGES (
    PACKAGE_ID        NUMBER PRIMARY KEY,
    PACKAGE_NAME      VARCHAR2(100),
    PRICE             NUMBER,
    AMOUNT_MINUTES    NUMBER,
    AMOUNT_DATA       NUMBER,
    AMOUNT_SMS        NUMBER,
    PERIOD            NUMBER
)TABLESPACE USERS;



--Kalan paket table'ı
CREATE TABLE BALANCE (
    CUSTOMER_ID        NUMBER PRIMARY KEY,
    PACKAGE_ID         NUMBER NOT NULL,
    REMAINING_MINUTES  NUMBER NOT NULL,
    REMAINING_SMS      NUMBER NOT NULL,
    REMAINING_DATA     NUMBER NOT NULL,
    START_DATE         TIMESTAMP NOT NULL,
    END_DATE           TIMESTAMP NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGE(PACKAGE_ID)
)TABLESPACE USERS;

--Müşteri
CREATE TABLE CUSTOMER (
    CUSTOMER_ID    NUMBER PRIMARY KEY,
    MSISDN         VARCHAR2(20) UNIQUE NOT NULL,
    NAME           VARCHAR2(100) NOT NULL,
    SURNAME        VARCHAR2(100) NOT NULL,
    EMAIL          VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD       VARCHAR2(100) NOT NULL,
    CREATED_AT     TIMESTAMP NOT NULL,
    NATIONAL_ID    VARCHAR2(11) UNIQUE NULL
)TABLESPACE USERS;


--Paket kullanımı
CREATE TABLE PERSONAL_USAGE (
    PERSONAL_USAGE_ID   NUMBER PRIMARY KEY,
    GIVER_MSISDN        VARCHAR2(20) NOT NULL,
    RECEIVER_MSISDN     VARCHAR2(20) ,
    USAGE_DATE          TIMESTAMP NOT NULL,
    USAGE_TYPE          VARCHAR2(10) NOT NULL,
    USAGE_DURATION      NUMBER NOT NULL,
    FOREIGN KEY (GIVER_MSISDN) REFERENCES CUSTOMER(MSISDN),
    FOREIGN KEY (RECEIVER_MSISDN) REFERENCES CUSTOMER(MSISDN)
)
TABLESPACE USERS;



--Bildirim Logları
CREATE TABLE NOTIFICATION_LOGS (
    NOTIFICATION_ID     NUMBER PRIMARY KEY,
    NOTIFICATION_TYPE   VARCHAR2(50) NOT NULL,
    NOTIFICATION_TIME   TIMESTAMP NOT NULL,
    CUSTOMER_ID         NUMBER NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
)TABLESPACE USERS;

--Giriş tarihçesi
CREATE TABLE LOGIN_HISTORY (
    LOGIN_ID     NUMBER PRIMARY KEY,
    CUSTOMER_ID  NUMBER NOT NULL,
    LOGIN_TIME   TIMESTAMP NOT NULL,
    DEVICE_TYPE  VARCHAR2(20) NOT NULL,
    IP_ADDRESS   VARCHAR2(50),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
)TABLESPACE USERS;


-- Dml Log
CREATE TABLE dml_multi_stage_log (
  operation_id     NUMBER,
  stage            NUMBER,
  table_name       VARCHAR2(100),
  operation        VARCHAR2(10),
  user_name        VARCHAR2(30),
  operation_time   TIMESTAMP DEFAULT SYSTIMESTAMP,
  status           VARCHAR2(20),      --'STARTED,PROCESSING' , 'SUCCESS' / 'FAILED'
  error_message    VARCHAR2(4000),    
  CONSTRAINT pk_dml_multi_stage PRIMARY KEY (operation_id, stage)
)TABLESPACE USERS;


--Password Change Verification
CREATE TABLE PASSWORD_RESET_CODES (
  RESET_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMAIL           VARCHAR2(320) NOT NULL,
  RESET_CODE      VARCHAR2(20) NOT NULL,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  EXPIRED_AT      TIMESTAMP NOT NULL,
  IS_USED         CHAR(1) DEFAULT 'N' CHECK (IS_USED IN ('Y', 'N')),
  USED_AT         TIMESTAMP,
  IP_ADDRESS      VARCHAR2(45),
  DEVICE_TYPE     VARCHAR2(20)
)TABLESPACE USERS;



CREATE TABLE INVOICE (
    INVOICE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID        NUMBER NOT NULL,
    PACKAGE_ID         NUMBER NOT NULL,
    START_DATE         TIMESTAMP NOT NULL,
    END_DATE           TIMESTAMP NOT NULL,
    PRICE              NUMBER NOT NULL,
    PAYMENT_STATUS     VARCHAR2(10) DEFAULT 'UNPAID' CHECK (PAYMENT_STATUS IN ('PAID', 'UNPAID')),

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PACKAGE_ID) REFERENCES SUBSCRIPTION_PACKAGES(PACKAGE_ID)
) TABLESPACE USERS;


--END TABLE CREATES

